plugins {
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.0.+'
}

version = '0.1.0-phase1'
group = 'com.tos.tosmod'

base {
    archivesName = 'tosmod'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

// Repositórios extra (necessário mais pra frente pra LuaJ na Fase 3)
repositories {
    mavenCentral()
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        logLevel = 'DEBUG'
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'tosmod'
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'tosmod'
        programArgument '--nogui'
    }

    data {
        programArguments.addAll '--mod', 'tosmod', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "net.neoforged:neoforge:21.1.+"

    // LuaJ - interpretador Lua 100% em Java (sem JNI/biblioteca nativa), usado no terminal do TOS.
    implementation 'org.luaj:luaj-jse:3.0.1'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: '1.21.1',
            neo_version      : '21.1.72',
            mod_id           : 'tosmod',
            mod_name         : 'TOS Mod',
            mod_version      : project.version
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}
