modLoader = "javafml"
loaderVersion = "[1,)"
license = "All rights reserved"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
TOS - Sistema modular de computadores, servidores e rede para NeoForge.
Fase 1: Hardware base (cases, slots, componentes).
'''

[[dependencies.'${mod_id}']]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.'${mod_id}']]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version},)"
    ordering = "NONE"
    side = "BOTH"
