modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="devicemod"
version="1.0.0"
displayName="MrCrayfish's Device Mod"
authors="MrCrayfish, Community"
description='''Adds working electronic devices with OS, WiFi, printer and programmable apps into Minecraft!'''

[[dependencies.devicemod]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.devicemod]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1]"
ordering="NONE"
side="BOTH"
